type QuestionType = {
  [key: string]: {
    [key: string]: number
  }
}
export const mpFeelingQuestions: QuestionType = {
  tenseLevel: {
    "Not at all": 0,
    "From time to time, occasionally": 1,
    "A lot of the time": 2,
    "Most of the time": 3,
  },
  frightenedLevel: {
    "Not at all": 0,
    "A little, but it doesn't worry me": 1,
    "Yes, but not too badly": 2,
    "Very definitely and quite badly": 3,
  },
  worryAmount: {
    "Only occasionally": 0,
    "From time to time, but not too often": 1,
    "A lot of the time": 2,
    "A great deal of the time": 3,
  },
  easeFrequency: {
    "Definitely": 0,
    "Usually": 1,
    "Not Often": 2,
    "Not at all": 3,
  },
  frightenedFrequency: {
    "Not at all": 0,
    "Occasionally": 1,
    "Quite Often": 2,
    "Very Often": 3,
  },
  restlessAmount: {
    "Not at all": 0,
    "Not very much": 1,
    "Quite a lot": 2,
    "Very much indeed": 3,
  },
  panicFrequency: {
    "Not at all": 0,
    "Not very often": 1,
    "Quite often": 2,
    "Very often indeed": 3,
  },
}

export const gsrsQuestions: QuestionType = {
  painOrDiscomfort: {
    "No discomfort at all": 0,
    "Minor discomfort": 1,
    "Mild discomfort": 2,
    "Moderate discomfort": 3,
    "Moderately severe discomfort": 4,
    "Severe discomfort": 5,
    "Very severe discomfort": 6,
  },
  acidReflux: {
    "No discomfort at all": 0,
    "Minor discomfort": 1,
    "Mild discomfort": 2,
    "Moderate discomfort": 3,
    "Moderately severe discomfort": 4,
    "Severe discomfort": 5,
    "Very severe discomfort": 6,
  },
  hungerPains: {
    "No discomfort at all": 0,
    "Minor discomfort": 1,
    "Mild discomfort": 2,
    "Moderate discomfort": 3,
    "Moderately severe discomfort": 4,
    "Severe discomfort": 5,
    "Very severe discomfort": 6,
  },
  nausea: {
    "No discomfort at all": 0,
    "Minor discomfort": 1,
    "Mild discomfort": 2,
    "Moderate discomfort": 3,
    "Moderately severe discomfort": 4,
    "Severe discomfort": 5,
    "Very severe discomfort": 6,
  },
  bloated: {
    "No discomfort at all": 0,
    "Minor discomfort": 1,
    "Mild discomfort": 2,
    "Moderate discomfort": 3,
    "Moderately severe discomfort": 4,
    "Severe discomfort": 5,
    "Very severe discomfort": 6,
  },
  burping: {
    "No discomfort at all": 0,
    "Minor discomfort": 1,
    "Mild discomfort": 2,
    "Moderate discomfort": 3,
    "Moderately severe discomfort": 4,
    "Severe discomfort": 5,
    "Very severe discomfort": 6,
  },
  constipation: {
    "No discomfort at all": 0,
    "Minor discomfort": 1,
    "Mild discomfort": 2,
    "Moderate discomfort": 3,
    "Moderately severe discomfort": 4,
    "Severe discomfort": 5,
    "Very severe discomfort": 6,
  },

  diarrhea: {
    "No discomfort at all": 0,
    "Minor discomfort": 1,
    "Mild discomfort": 2,
    "Moderate discomfort": 3,
    "Moderately severe discomfort": 4,
    "Severe discomfort": 5,
    "Very severe discomfort": 6,
  },
  looseStools: {
    "No discomfort at all": 0,
    "Minor discomfort": 1,
    "Mild discomfort": 2,
    "Moderate discomfort": 3,
    "Moderately severe discomfort": 4,
    "Severe discomfort": 5,
    "Very severe discomfort": 6,
  },
  gas: {
    "No discomfort at all": 0,
    "Minor discomfort": 1,
    "Mild discomfort": 2,
    "Moderate discomfort": 3,
    "Moderately severe discomfort": 4,
    "Severe discomfort": 5,
    "Very severe discomfort": 6,
  },
  hardStools: {
    "No discomfort at all": 0,
    "Minor discomfort": 1,
    "Mild discomfort": 2,
    "Moderate discomfort": 3,
    "Moderately severe discomfort": 4,
    "Severe discomfort": 5,
    "Very severe discomfort": 6,
  },
  urgentBowel: {
    "No discomfort at all": 0,
    "Minor discomfort": 1,
    "Mild discomfort": 2,
    "Moderate discomfort": 3,
    "Moderately severe discomfort": 4,
    "Severe discomfort": 5,
    "Very severe discomfort": 6,
  },
  completeBowels: {
    "No discomfort at all": 0,
    "Minor discomfort": 1,
    "Mild discomfort": 2,
    "Moderate discomfort": 3,
    "Moderately severe discomfort": 4,
    "Severe discomfort": 5,
    "Very severe discomfort": 6,
  },
  heartBurn: {
    "No discomfort at all": 0,
    "Minor discomfort": 1,
    "Mild discomfort": 2,
    "Moderate discomfort": 3,
    "Moderately severe discomfort": 4,
    "Severe discomfort": 5,
    "Very severe discomfort": 6,
  },

  rumbling: {
    "No discomfort at all": 0,
    "Minor discomfort": 1,
    "Mild discomfort": 2,
    "Moderate discomfort": 3,
    "Moderately severe discomfort": 4,
    "Severe discomfort": 5,
    "Very severe discomfort": 6,
  },
}
export const tefqQuestions: QuestionType = {
  alwaysEating: {
    "Definitely false": 0,
    "Mostly false": 1,
    "Mostly true": 2,
    "Definitely true": 3,
  },
  smallHelpings: {
    "Definitely false": 0,
    "Mostly false": 1,
    "Mostly true": 2,
    "Definitely true": 3,
  },
  anxiousEating: {
    "Definitely false": 0,
    "Mostly false": 1,
    "Mostly true": 2,
    "Definitely true": 3,
  },
  uncontrollableEating: {
    "Definitely false": 0,
    "Mostly false": 1,
    "Mostly true": 2,
    "Definitely true": 3,
  },
  eatingWithOthers: {
    "Definitely false": 0,
    "Mostly false": 1,
    "Mostly true": 2,
    "Definitely true": 3,
  },
  overeatingWhenBlue: {
    "Definitely false": 0,
    "Mostly false": 1,
    "Mostly true": 2,
    "Definitely true": 3,
  },
  bottomlessPit: {
    "Definitely false": 0,
    "Mostly false": 1,
    "Mostly true": 2,
    "Definitely true": 3,
  },
  alwaysHungry: {
    "Definitely false": 0,
    "Mostly false": 1,
    "Mostly true": 2,
    "Definitely true": 3,
  },
  holdBack: {
    "Definitely false": 0,
    "Mostly false": 1,
    "Mostly true": 2,
    "Definitely true": 3,
  },
  fatFoods: {
    "Definitely false": 0,
    "Mostly false": 1,
    "Mostly true": 2,
    "Definitely true": 3,
  },
  alwaysHungry2: {
    "Definitely false": 0,
    "Mostly false": 1,
    "Mostly true": 2,
    "Definitely true": 3,
  },
  howOftenHungry: {
    "Only at meal times": 0,
    "Sometimes between meals": 1,
    "Often between meals": 2,
    "Almost always": 3,
  },
  avoidStockingUp: {
    "Definitely false": 0,
    "Mostly false": 1,
    "Mostly true": 2,
    "Definitely true": 3,
  },
  conciouslyEatLess: {
    "Unlikely": 0,
    "Slightly likely": 1,
    "Moderately likely": 2,
    "Very likely": 3,
  },
  eatingBinges: {
    "Never": 0,
    "Rarely": 1,
    "Sometimes": 2,
    "At least once a week": 3,
  },
  delicacyEating: {
    "Definitely false": 0,
    "Mostly false": 1,
    "Mostly true": 2,
    "Definitely true": 3,
  },
  lonelyEating: {
    "Definitely false": 0,
    "Mostly false": 1,
    "Mostly true": 2,
    "Definitely true": 3,
  },
}
